[2024-08-24T20:05:18.876+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T20:05:18.905+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task manual__2024-08-24T20:05:16.860622+00:00 [queued]>
[2024-08-24T20:05:18.917+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task manual__2024-08-24T20:05:16.860622+00:00 [queued]>
[2024-08-24T20:05:18.918+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T20:05:18.938+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): first_task> on 2024-08-24 20:05:16.860622+00:00
[2024-08-24T20:05:18.944+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6604) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T20:05:18.949+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'first_task', 'manual__2024-08-24T20:05:16.860622+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpa1pqc7td']
[2024-08-24T20:05:18.953+0000] {standard_task_runner.py:72} INFO - Started process 6605 to run task
[2024-08-24T20:05:18.953+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask first_task
[2024-08-24T20:05:19.011+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v5.first_task manual__2024-08-24T20:05:16.860622+00:00 [running]> on host 90ca7eb2d7b6
[2024-08-24T20:05:19.109+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shreyas' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T20:05:16.860622+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T20:05:16.860622+00:00'
[2024-08-24T20:05:19.111+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T20:05:19.188+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-24T20:05:19.191+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2024-08-24T20:05:19.208+0000] {subprocess.py:86} INFO - Output:
[2024-08-24T20:05:19.247+0000] {subprocess.py:93} INFO - hello world, this is the first task!
[2024-08-24T20:05:19.249+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-24T20:05:19.301+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T20:05:19.302+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=first_task, run_id=manual__2024-08-24T20:05:16.860622+00:00, execution_date=20240824T200516, start_date=20240824T200518, end_date=20240824T200519
[2024-08-24T20:05:19.347+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-24T20:05:19.383+0000] {taskinstance.py:3891} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-08-24T20:05:19.388+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
