[2024-08-25T08:31:31.913+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T08:31:31.944+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill_v2.task1 manual__2024-08-25T08:31:29.578919+00:00 [queued]>
[2024-08-25T08:31:31.961+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill_v2.task1 manual__2024-08-25T08:31:29.578919+00:00 [queued]>
[2024-08-25T08:31:31.963+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-08-25T08:31:31.994+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): task1> on 2024-08-25 08:31:29.578919+00:00
[2024-08-25T08:31:32.001+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1663) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-25T08:31:32.004+0000] {standard_task_runner.py:72} INFO - Started process 1664 to run task
[2024-08-25T08:31:32.006+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill_v2', 'task1', 'manual__2024-08-25T08:31:29.578919+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmprqc9q22k']
[2024-08-25T08:31:32.008+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask task1
[2024-08-25T08:31:32.091+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill_v2.task1 manual__2024-08-25T08:31:29.578919+00:00 [running]> on host ae952724060e
[2024-08-25T08:31:32.255+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shreyas' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill_v2' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T08:31:29.578919+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T08:31:29.578919+00:00'
[2024-08-25T08:31:32.257+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T08:31:32.281+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-25T08:31:32.283+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2024-08-25T08:31:32.302+0000] {subprocess.py:86} INFO - Output:
[2024-08-25T08:31:32.304+0000] {subprocess.py:93} INFO - This is a simple bash command!
[2024-08-25T08:31:32.306+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-25T08:31:32.373+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T08:31:32.374+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill_v2, task_id=task1, run_id=manual__2024-08-25T08:31:29.578919+00:00, execution_date=20240825T083129, start_date=20240825T083131, end_date=20240825T083132
[2024-08-25T08:31:32.429+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T08:31:32.464+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T08:31:32.468+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
