[2024-08-25T15:06:04.456+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T15:06:04.501+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigquery_dag.check_file manual__2024-08-25T15:05:45.342662+00:00 [queued]>
[2024-08-25T15:06:04.527+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigquery_dag.check_file manual__2024-08-25T15:05:45.342662+00:00 [queued]>
[2024-08-25T15:06:04.529+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-25T15:06:04.570+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): check_file> on 2024-08-25 15:05:45.342662+00:00
[2024-08-25T15:06:04.587+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6933) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-25T15:06:04.592+0000] {standard_task_runner.py:72} INFO - Started process 6936 to run task
[2024-08-25T15:06:04.594+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bigquery_dag', 'check_file', 'manual__2024-08-25T15:05:45.342662+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/gcp_integration_dag.py', '--cfg-path', '/tmp/tmp_nlm2ieb']
[2024-08-25T15:06:04.599+0000] {standard_task_runner.py:105} INFO - Job 138: Subtask check_file
[2024-08-25T15:06:04.725+0000] {task_command.py:467} INFO - Running <TaskInstance: bigquery_dag.check_file manual__2024-08-25T15:05:45.342662+00:00 [running]> on host ae952724060e
[2024-08-25T15:06:04.970+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sss' AIRFLOW_CTX_DAG_ID='bigquery_dag' AIRFLOW_CTX_TASK_ID='check_file' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T15:05:45.342662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T15:05:45.342662+00:00'
[2024-08-25T15:06:04.973+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T15:06:04.979+0000] {logging_mixin.py:190} INFO - File does not exist
[2024-08-25T15:06:04.980+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-25T15:06:05.007+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T15:06:05.008+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=bigquery_dag, task_id=check_file, run_id=manual__2024-08-25T15:05:45.342662+00:00, execution_date=20240825T150545, start_date=20240825T150604, end_date=20240825T150605
[2024-08-25T15:06:05.095+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T15:06:05.121+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T15:06:05.125+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
