[2024-08-25T15:20:51.917+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T15:20:51.961+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigquery_dag.check_file manual__2024-08-25T15:20:47.101923+00:00 [queued]>
[2024-08-25T15:20:51.975+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigquery_dag.check_file manual__2024-08-25T15:20:47.101923+00:00 [queued]>
[2024-08-25T15:20:51.976+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-25T15:20:52.014+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): check_file> on 2024-08-25 15:20:47.101923+00:00
[2024-08-25T15:20:52.033+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-25T15:20:52.035+0000] {standard_task_runner.py:72} INFO - Started process 7153 to run task
[2024-08-25T15:20:52.036+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bigquery_dag', 'check_file', 'manual__2024-08-25T15:20:47.101923+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/gcp_integration_dag.py', '--cfg-path', '/tmp/tmp2fwrtchk']
[2024-08-25T15:20:52.041+0000] {standard_task_runner.py:105} INFO - Job 147: Subtask check_file
[2024-08-25T15:20:52.146+0000] {task_command.py:467} INFO - Running <TaskInstance: bigquery_dag.check_file manual__2024-08-25T15:20:47.101923+00:00 [running]> on host ae952724060e
[2024-08-25T15:20:52.317+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sss_af' AIRFLOW_CTX_DAG_ID='bigquery_dag' AIRFLOW_CTX_TASK_ID='check_file' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T15:20:47.101923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T15:20:47.101923+00:00'
[2024-08-25T15:20:52.322+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T15:20:52.327+0000] {logging_mixin.py:190} INFO - File does not exist
[2024-08-25T15:20:52.328+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-25T15:20:52.346+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T15:20:52.347+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=bigquery_dag, task_id=check_file, run_id=manual__2024-08-25T15:20:47.101923+00:00, execution_date=20240825T152047, start_date=20240825T152051, end_date=20240825T152052
[2024-08-25T15:20:52.416+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T15:20:52.433+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
